/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "D:\\myprogram\\vueblog\\recodemo\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-6622e26c",
    path: "/theme-reco/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6622e26c").then(next)
    },
  },
  {
    path: "/theme-reco/index.html",
    redirect: "/theme-reco/"
  },
  {
    name: "v-1c68e5f1",
    path: "/theme-reco/api.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1c68e5f1").then(next)
    },
  },
  {
    name: "v-9815c47e",
    path: "/theme-reco/plugin.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-9815c47e").then(next)
    },
  },
  {
    name: "v-9977205a",
    path: "/theme-reco/theme.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-9977205a").then(next)
    },
  },
  {
    path: '*',
    component: GlobalLayout
  }
]