/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "",
  "description": "",
  "base": "/",
  "headTags": [],
  "pages": [
    {
      "title": "theme-reco",
      "frontmatter": {
        "title": "theme-reco",
        "date": "2020-05-29T00:00:00.000Z"
      },
      "regularPath": "/theme-reco/",
      "relativePath": "theme-reco/README.md",
      "key": "v-6622e26c",
      "path": "/theme-reco/"
    },
    {
      "title": "api",
      "frontmatter": {
        "title": "api",
        "date": "2020-05-29T00:00:00.000Z"
      },
      "regularPath": "/theme-reco/api.html",
      "relativePath": "theme-reco/api.md",
      "key": "v-1c68e5f1",
      "path": "/theme-reco/api.html"
    },
    {
      "title": "plugin",
      "frontmatter": {
        "title": "plugin",
        "date": "2020-05-28T00:00:00.000Z"
      },
      "regularPath": "/theme-reco/plugin.html",
      "relativePath": "theme-reco/plugin.md",
      "key": "v-9815c47e",
      "path": "/theme-reco/plugin.html"
    },
    {
      "title": "theme",
      "frontmatter": {
        "title": "theme",
        "date": "2020-05-27T00:00:00.000Z"
      },
      "regularPath": "/theme-reco/theme.html",
      "relativePath": "theme-reco/theme.md",
      "key": "v-9977205a",
      "path": "/theme-reco/theme.html"
    }
  ],
  "themeConfig": {}
}